/open Server.java
/open SelfCheckout.java
/open Customer.java
/open Event.java
/open Shop.java
/open Pair.java
/open ArriveEvent.java
/open ServeEvent.java
/open WaitEvent.java
/open DoneEvent.java
/open LeaveEvent.java
/open SERVER_REST.java
/open SERVER_BACK.java
/open Simulation.java
/open Statistics.java
/open Main.java
